#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jul 23, 2018 10:02:46 PM

import main
_winners = []
position = 1
_records = None

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import GUI_support

def vp_start_gui(winnersRef, recordsRef):
    global _winners
    global _records
    _records = recordsRef
    _winners = winnersRef
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    GUI_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    GUI_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None





class New_Toplevel:


    def test(self):
        global position
        global _winners
        if position == 4:
            position = 0
            main.reset(_records)
        self.newWinner(position)
        position += 1



    def newWinner(self, currentPosition):
        if currentPosition == 0:
            self.first = PhotoImage(file=str("logosresized/" + 'default' + ".png"))
            self.Label2.configure(image=self.first)
            self.second = PhotoImage(file=str("logosresized/" + 'default' + ".png"))
            self.Label2_1.configure(image=self.second)
            self.third = PhotoImage(file=str("logosresized/" + 'default' + ".png"))
            self.Label2_2.configure(image=self.third)
            self.Button1.configure(text='GENERATE')
        elif currentPosition == 1:
            self.first = PhotoImage(file=str("logosresized/" + _winners[0] + ".png"))
            self.Label2.configure(image=self.first)
        elif currentPosition == 2:
            self.second = PhotoImage(file=str("logosresized/" + _winners[1] + ".png"))
            self.Label2_1.configure(image=self.second)
        elif currentPosition == 3:
            self.third = PhotoImage(file=str("logosresized/" + _winners[2] + ".png"))
            self.Label2_2.configure(image=self.third)
            self.Button1.configure(text='RESET')



    def __init__(self, top=None):
        currentPosition = 0
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font14 = "-family {Gill Sans Ultra Bold} -size 9 -weight "  \
            "normal -slant roman -underline 0 -overstrike 0"
        font15 = "-family {Gill Sans Ultra Bold} -size 13 -weight bold"  \
            " -slant roman -underline 0 -overstrike 0"

        top.geometry("600x450+641+191")
        top.title("NHL Lottery Simulator")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = Label(top)
        self.Label1.place(relx=0.34, rely=0.96, height=16, width=192)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font14)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Click To Generate''')
        self.Label1.configure(width=500)

        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.02, rely=0.13, relheight=0.54
                , relwidth=0.97)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=580)

        self.Label2 = Label(self.Labelframe1)
        self.Label2.place(relx=0.01, rely=0.17, height=156, width=182, y=-16)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.first = PhotoImage(file="logosresized/default.png")
        self.Label2.configure(image=self.first)
        self.Label2.configure(text='''Label''')
        self.Label2.configure(width=182)

        self.Label2_1 = Label(self.Labelframe1)
        self.Label2_1.place(relx=0.34, rely=0.17, height=156, width=182, y=-16)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#d9d9d9")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.second = PhotoImage(file="logosresized/default.png")
        self.Label2_1.configure(image=self.second)
        self.Label2_1.configure(text='''Label''')

        self.Label2_2 = Label(self.Labelframe1)
        self.Label2_2.place(relx=0.67, rely=0.17, height=156, width=182, y=-16)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#d9d9d9")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.third = PhotoImage(file="logosresized/default.png")
        self.Label2_2.configure(image=self.third)
        self.Label2_2.configure(text='''Label''')

        self.Label3 = Label(self.Labelframe1)
        self.Label3.place(relx=0.095, rely=0.82, height=48, width=84, y=-16)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font15)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''First''')
        self.Label3.configure(width=84)

        self.Label3_3 = Label(self.Labelframe1)
        self.Label3_3.place(relx=0.4, rely=0.8, height=58, width=114, y=-16)

        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#d9d9d9")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(font=font15)
        self.Label3_3.configure(foreground="#000000")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''Second''')
        self.Label3_3.configure(width=114)

        self.Label3_4 = Label(self.Labelframe1)
        self.Label3_4.place(relx=0.73, rely=0.79, height=58, width=114, y=-16)
        self.Label3_4.configure(activebackground="#f9f9f9")
        self.Label3_4.configure(activeforeground="black")
        self.Label3_4.configure(background="#d9d9d9")
        #self.Label3_4.configure(disabledforeground="#a3a3a3")
        self.Label3_4.configure(font=font15)
        #self.Label3_4.configure(foreground="#000000")
        self.Label3_4.configure(highlightbackground="#d9d9d9")
        self.Label3_4.configure(highlightcolor="black")
        self.Label3_4.configure(text='''Third''')

        self.currentPosition = 0
        self.Button1 = Button(top, command=self.test)
        self.Button1.place(relx=0.43, rely=0.73, height=55, width=85)
        self.Button1.configure(text="GENERATE")
        self.Button1.configure(pady="0")





#
#
# if __name__ == '__main__':
#     vp_start_gui()



